a=float(input("Enter Value For a  :"))
b=float(input("Enter Value For b  :"))

print("="*50)
print("\tArithmatic Operatores")
print("="*50)
print("\tAddition :{} and {} ={}".format(a,b,a+b))
print("\tSubtraction :{} and {} ={}".format(a,b,a-b))
print("\tDivision :{} and {} ={}".format(a,b,a/b))
print("\tMultiplication :{} and {} ={}".format(a,b,a*b))
print("\tModulo Div :{} and {} ={}".format(a,b,a//b))
print("\tExponantion :{} and {} ={}".format(a,b,a**b))
print("\tReaminder :{} and {} ={}".format(a,b,a%b))
print("="*50)